site_name: SDET Bootcamp (sdetkit)
repo_url: https://github.com/sherif69-sa/sdet_bootcamp
theme:
  name: material
plugins:
  - search
nav:
  - Home: index.md
  - Project structure: project-structure.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
